GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJuYW1lIjoiYWRtaW4iLCJpZCI6IjY0MWFkZTMyMTFmN2M4NGY2OTkxZDBkOSIsImlhdCI6MTY4NDkyNDQwMSwiZXhwIjoxNjg0OTI4MDAxfQ.Vq6VbVpIGpzlE-r-PoBeMXSjRu6s7HkUbx-fgJsKrMg

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbCIsIm5hbWUiOiJkYW5pZWwiLCJpZCI6IjY0MWIxNWRlYmZkOWQ2ZDkzZDg5ZDY3YiIsImlhdCI6MTY3OTQ5NzU2OSwiZXhwIjoxNjc5NDk4MTY5fQ.V_Lcf0s4xhGOAF7oFut1K8PzqT7MEjPBGu8ZpJvzh90

{
    "title": "jwt is very interesting",
    "author": "daniel",
    "url": "daniel.com/blog/2",
    "likes": 0
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "7th interesting blog",
    "author": "root",
    "url": "root.com/blog/1",
    "likes": 123456
}

###
POST http://localhost:3003/api/blogs/641b04e367119c9669bef34b/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJuYW1lIjoiYWRtaW4iLCJpZCI6IjY0MWFkZTMyMTFmN2M4NGY2OTkxZDBkOSIsImlhdCI6MTY4NDkyNDQwMSwiZXhwIjoxNjg0OTI4MDAxfQ.Vq6VbVpIGpzlE-r-PoBeMXSjRu6s7HkUbx-fgJsKrMg

{
    "comment": "test comment from rest"
}

###
DELETE http://localhost:3003/api/blogs/641b1973221c838c3b3a11f4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbCIsIm5hbWUiOiJkYW5pZWwiLCJpZCI6IjY0MWIxNWRlYmZkOWQ2ZDkzZDg5ZDY3YiIsImlhdCI6MTY3OTQ5NzU2OSwiZXhwIjoxNjc5NDk4MTY5fQ.V_Lcf0s4xhGOAF7oFut1K8PzqT7MEjPBGu8ZpJvzh90

###
PUT http://localhost:3003/api/blogs/6419533d77649ca4ed310bc5
Content-Type: application/json

{
    "title": "Third interesting blog",
    "author": "Ying Tu",
    "likes": 156
}
